sudo: false
language: python

env:
    global:
        - COMMIT_AUTHOR_EMAIL: b.f.van.beek@vu.nl
    matrix:
        - PYTHON_VERSION=3.6
        - PYTHON_VERSION=3.7

install:
    # Install python
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
    - conda update -q conda

    # Useful for debugging any issues with conda
    - conda info -a

    # Install virtual enviroment
    - conda create -n CAT python=${PYTHON_VERSION}
    - conda install -n CAT -c conda-forge h5py rdkit
    - source activate CAT

    # Install tests, data-CAT and nano-CAT
    - pip install .[test]
    - pip install nano-cat@git+https://github.com/nlesc-nano/nano-CAT@devel --upgrade
    - pip install data-cat@git+https://github.com/nlesc-nano/data-CAT@devel --upgrade

script:
    # Run the unitary tests excluding the expensive computations
    - pytest -m "not (slow or long)" --cov=CAT tests
    - coverage xml && coverage report -m

branches:
    only:
        - master
